image: node

before_script:
  - npm install

pages:
  stage: deploy
  script:
    - mkdir public
    - $(npm bin)/webpack
    - cp dist/bundle.js public/
    - cp examples/index.html public/
  artifacts:
    paths:
      - public
